name: Build and DB Schema Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-qt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ secrets.QT_VERSION }}

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y cmake build-essential libpq-dev

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build

  db-schema-check:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v4

    - name: Wait for Postgres
      run: |
        until pg_isready -h localhost -p 5432 -U postgres; do sleep 1; done

    - name: Apply schema
      env:
        PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      run: |
        psql -h localhost -U postgres -f db/schema.sql
